export const TOOLS = [
  {
    slug: 'comprimir-pdf',
    name: 'Comprimir PDF',
    shortName: 'Comprimir',
    description: 'Reduza o tamanho do PDF sem perder qualidade. Ideal para enviar por e-mail ou WhatsApp.',
    icon: '🗜️',
    color: 'bg-blue-50',
    iconBg: 'bg-blue-100',
    keywords: ['comprimir pdf', 'reduzir pdf', 'pdf menor'],
  },
  {
    slug: 'converter-pdf-para-word',
    name: 'PDF para Word',
    shortName: 'PDF para Word',
    description: 'Transforme PDF em documento Word editável (.docx) em segundos.',
    icon: '📄',
    color: 'bg-indigo-50',
    iconBg: 'bg-indigo-100',
    keywords: ['pdf para word', 'converter pdf word', 'pdf docx'],
  },
  {
    slug: 'converter-pdf-para-jpg',
    name: 'PDF para JPG',
    shortName: 'PDF para JPG',
    description: 'Converta cada página do PDF em imagem JPG de alta qualidade.',
    icon: '🖼️',
    color: 'bg-green-50',
    iconBg: 'bg-green-100',
    keywords: ['pdf para jpg', 'pdf para imagem', 'converter pdf jpg'],
  },
  {
    slug: 'converter-word-para-pdf',
    name: 'Word para PDF',
    shortName: 'Word para PDF',
    description: 'Transforme documentos Word (.docx) em PDF preservando a formatação.',
    icon: '📝',
    color: 'bg-purple-50',
    iconBg: 'bg-purple-100',
    keywords: ['word para pdf', 'docx para pdf', 'converter word pdf'],
  },
  {
    slug: 'converter-jpg-para-pdf',
    name: 'Imagem para PDF',
    shortName: 'Imagem para PDF',
    description: 'Junte fotos e imagens JPG/PNG em um único documento PDF.',
    icon: '📷',
    color: 'bg-yellow-50',
    iconBg: 'bg-yellow-100',
    keywords: ['imagem para pdf', 'jpg para pdf', 'foto para pdf'],
  },
  {
    slug: 'juntar-pdf',
    name: 'Juntar PDF',
    shortName: 'Juntar PDF',
    description: 'Una vários arquivos PDF em um só documento na ordem que desejar.',
    icon: '🔗',
    color: 'bg-orange-50',
    iconBg: 'bg-orange-100',
    keywords: ['juntar pdf', 'unir pdf', 'mesclar pdf'],
  },
  {
    slug: 'dividir-pdf',
    name: 'Dividir PDF',
    shortName: 'Dividir PDF',
    description: 'Separe páginas de um PDF ou extraia um intervalo específico.',
    icon: '✂️',
    color: 'bg-red-50',
    iconBg: 'bg-red-100',
    keywords: ['dividir pdf', 'separar pdf', 'extrair página pdf'],
  },
];
