export interface ToolItem {
  slug: string;
  name: string;
  shortName: string;
  description: string;
  icon: string;
  color: string;
  iconBg: string;
  category: 'pdf' | 'conversao' | 'edicao' | 'ocr';
  keywords: string[];
}

export const CATEGORIES_CONFIG = [
  { id: 'pdf', name: 'Ferramentas PDF', icon: '🛠️', description: 'Comprimir, juntar, dividir, girar, organizar e proteger documentos.' },
  { id: 'conversao', name: 'Conversão de Arquivos', icon: '🔄', description: 'Converta PDFs para Word, Imagens, Excel, PowerPoint e vice-versa.' },
  { id: 'edicao', name: 'Edição de PDF', icon: '✏️', description: 'Assinar, adicionar texto, marca d’água e preencher formulários.' },
  { id: 'ocr', name: 'OCR & Transcrição', icon: '🎙️', description: 'Extraia textos de PDFs escaneados, fotos e transcrição de áudio e vídeo.' },
] as const;

export const TOOLS: ToolItem[] = [
  // ── FERRAMENTAS PDF ────────────────────────────────────────────────────────
  {
    slug: 'comprimir-pdf',
    name: 'Comprimir PDF',
    shortName: 'Comprimir',
    description: 'Reduza o tamanho do PDF mantendo a qualidade visual. Ideal para enviar por e-mail ou WhatsApp.',
    icon: '🗜️',
    color: 'bg-blue-50',
    iconBg: 'bg-blue-100 text-blue-600',
    category: 'pdf',
    keywords: ['comprimir pdf', 'reduzir pdf', 'pdf menor', 'comprimir pdf whatsapp'],
  },
  {
    slug: 'juntar-pdf',
    name: 'Juntar PDF',
    shortName: 'Juntar PDF',
    description: 'Una vários arquivos PDF em um só documento organizado na ordem que desejar.',
    icon: '🔗',
    color: 'bg-orange-50',
    iconBg: 'bg-orange-100 text-orange-600',
    category: 'pdf',
    keywords: ['juntar pdf', 'unir pdf', 'mesclar pdf', 'combinar pdf'],
  },
  {
    slug: 'dividir-pdf',
    name: 'Dividir PDF',
    shortName: 'Dividir PDF',
    description: 'Separe páginas de um PDF ou extraia intervalos específicos em arquivos independentes.',
    icon: '✂️',
    color: 'bg-red-50',
    iconBg: 'bg-red-100 text-red-600',
    category: 'pdf',
    keywords: ['dividir pdf', 'separar pdf', 'extrair página pdf', 'cortar pdf'],
  },
  {
    slug: 'girar-pdf',
    name: 'Girar PDF',
    shortName: 'Girar PDF',
    description: 'Rotacione páginas de PDF para orientação retrato ou paisagem com facilidade.',
    icon: '🔄',
    color: 'bg-indigo-50',
    iconBg: 'bg-indigo-100 text-indigo-600',
    category: 'pdf',
    keywords: ['girar pdf', 'rotacionar pdf', 'virar página pdf', 'inverter pdf'],
  },
  {
    slug: 'remover-paginas-pdf',
    name: 'Remover Páginas',
    shortName: 'Remover Páginas',
    description: 'Exclua folhas desnecessárias de um documento PDF em segundos.',
    icon: '🗑️',
    color: 'bg-rose-50',
    iconBg: 'bg-rose-100 text-rose-600',
    category: 'pdf',
    keywords: ['remover páginas pdf', 'apagar folha pdf', 'excluir página pdf'],
  },
  {
    slug: 'extrair-paginas-pdf',
    name: 'Extrair Páginas',
    shortName: 'Extrair Páginas',
    description: 'Isole apenas as folhas de seu interesse de um contrato ou livro pesado.',
    icon: '📄',
    color: 'bg-sky-50',
    iconBg: 'bg-sky-100 text-sky-600',
    category: 'pdf',
    keywords: ['extrair páginas pdf', 'destacar folhas pdf', 'isolar páginas pdf'],
  },
  {
    slug: 'reordenar-paginas-pdf',
    name: 'Reordenar Páginas',
    shortName: 'Reordenar Páginas',
    description: 'Altere a ordem de exibição das páginas do seu PDF do jeito que precisar.',
    icon: '🔀',
    color: 'bg-teal-50',
    iconBg: 'bg-teal-100 text-teal-600',
    category: 'pdf',
    keywords: ['reordenar páginas pdf', 'mudar ordem pdf', 'organizar folhas pdf'],
  },
  {
    slug: 'proteger-pdf',
    name: 'Proteger PDF com Senha',
    shortName: 'Proteger PDF',
    description: 'Adicione uma senha forte de criptografia ao seu PDF para impedir acessos não autorizados.',
    icon: '🔒',
    color: 'bg-slate-50',
    iconBg: 'bg-slate-100 text-slate-700',
    category: 'pdf',
    keywords: ['proteger pdf com senha', 'senha para pdf', 'bloquear pdf', 'criptografar pdf'],
  },
  {
    slug: 'desbloquear-pdf',
    name: 'Desbloquear PDF',
    shortName: 'Desbloquear PDF',
    description: 'Remova a senha de arquivos PDF quando você tiver a devida autorização de acesso.',
    icon: '🔓',
    color: 'bg-amber-50',
    iconBg: 'bg-amber-100 text-amber-600',
    category: 'pdf',
    keywords: ['desbloquear pdf', 'remover senha pdf', 'tirar senha de pdf'],
  },

  // ── CONVERSÃO DE ARQUIVOS ──────────────────────────────────────────────────
  {
    slug: 'converter-pdf-para-word',
    name: 'PDF para Word',
    shortName: 'PDF para Word',
    description: 'Transforme PDF em documento Word editável (.docx) preservando formatação e texto.',
    icon: '📝',
    color: 'bg-indigo-50',
    iconBg: 'bg-indigo-100 text-indigo-600',
    category: 'conversao',
    keywords: ['pdf para word', 'converter pdf word', 'pdf docx', 'pdf editável'],
  },
  {
    slug: 'converter-pdf-para-jpg',
    name: 'PDF para JPG',
    shortName: 'PDF para JPG',
    description: 'Converta cada página do PDF em imagens JPG de alta qualidade prontas para compartilhamento.',
    icon: '🖼️',
    color: 'bg-green-50',
    iconBg: 'bg-green-100 text-green-600',
    category: 'conversao',
    keywords: ['pdf para jpg', 'pdf para imagem', 'converter pdf foto'],
  },
  {
    slug: 'converter-pdf-para-png',
    name: 'PDF para PNG',
    shortName: 'PDF para PNG',
    description: 'Exporte páginas de PDF em formato de imagem PNG com transparência e altíssima resolução.',
    icon: '🎨',
    color: 'bg-emerald-50',
    iconBg: 'bg-emerald-100 text-emerald-600',
    category: 'conversao',
    keywords: ['pdf para png', 'converter pdf png', 'imagem png pdf'],
  },
  {
    slug: 'converter-pdf-para-excel',
    name: 'PDF para Excel',
    shortName: 'PDF para Excel',
    description: 'Extraia tabelas e dados numéricos de arquivos PDF para planilhas editáveis (.xlsx).',
    icon: '📊',
    color: 'bg-emerald-50',
    iconBg: 'bg-emerald-100 text-emerald-700',
    category: 'conversao',
    keywords: ['pdf para excel', 'pdf para xlsx', 'extrair tabela pdf excel'],
  },
  {
    slug: 'converter-pdf-para-powerpoint',
    name: 'PDF para PowerPoint',
    shortName: 'PDF para PPT',
    description: 'Transforme apresentações em PDF em slides editáveis do PowerPoint (.pptx).',
    icon: '📊',
    color: 'bg-orange-50',
    iconBg: 'bg-orange-100 text-orange-700',
    category: 'conversao',
    keywords: ['pdf para powerpoint', 'pdf para ppt', 'slides pdf pptx'],
  },
  {
    slug: 'converter-word-para-pdf',
    name: 'Word para PDF',
    shortName: 'Word para PDF',
    description: 'Transforme documentos Word (.docx ou .doc) em PDF mantendo fontes e margens intactas.',
    icon: '📘',
    color: 'bg-purple-50',
    iconBg: 'bg-purple-100 text-purple-600',
    category: 'conversao',
    keywords: ['word para pdf', 'docx para pdf', 'converter word pdf'],
  },
  {
    slug: 'converter-jpg-para-pdf',
    name: 'JPG para PDF',
    shortName: 'JPG para PDF',
    description: 'Junte fotos JPG em um único arquivo PDF organizado e pronto para impressão.',
    icon: '📷',
    color: 'bg-yellow-50',
    iconBg: 'bg-yellow-100 text-yellow-700',
    category: 'conversao',
    keywords: ['jpg para pdf', 'foto para pdf', 'converter jpg em pdf'],
  },
  {
    slug: 'converter-png-para-pdf',
    name: 'PNG para PDF',
    shortName: 'PNG para PDF',
    description: 'Converta imagens PNG em documentos PDF de alta definição sem perda de nitidez.',
    icon: '🖼️',
    color: 'bg-lime-50',
    iconBg: 'bg-lime-100 text-lime-700',
    category: 'conversao',
    keywords: ['png para pdf', 'imagem png pdf', 'converter png pdf'],
  },
  {
    slug: 'converter-imagem-para-pdf',
    name: 'Imagens para PDF',
    shortName: 'Imagens para PDF',
    description: 'Unifique múltiplos formatos de fotos (JPG, PNG, WebP) em um documento PDF completo.',
    icon: '📸',
    color: 'bg-amber-50',
    iconBg: 'bg-amber-100 text-amber-700',
    category: 'conversao',
    keywords: ['imagens para pdf', 'converter fotos pdf', 'juntar fotos em pdf'],
  },

  // ── EDIÇÃO DE PDF ─────────────────────────────────────────────────────────
  {
    slug: 'editar-pdf',
    name: 'Editar PDF',
    shortName: 'Editar PDF',
    description: 'Adicione anotações, edite textos e formate seu documento PDF diretamente no navegador.',
    icon: '✏️',
    color: 'bg-cyan-50',
    iconBg: 'bg-cyan-100 text-cyan-700',
    category: 'edicao',
    keywords: ['editar pdf', 'editor de pdf online', 'modificar pdf'],
  },
  {
    slug: 'adicionar-texto-pdf',
    name: 'Adicionar Texto ao PDF',
    shortName: 'Adicionar Texto',
    description: 'Escreva novos parágrafos, cabeçalhos ou observações em seu arquivo PDF.',
    icon: '🔤',
    color: 'bg-sky-50',
    iconBg: 'bg-sky-100 text-sky-700',
    category: 'edicao',
    keywords: ['adicionar texto pdf', 'escrever no pdf', 'inserir texto pdf'],
  },
  {
    slug: 'adicionar-imagem-pdf',
    name: 'Adicionar Imagem ao PDF',
    shortName: 'Adicionar Imagem',
    description: 'Insira logotipos, selos, fotos e figuras dentro de qualquer página de seu PDF.',
    icon: '🖼️',
    color: 'bg-blue-50',
    iconBg: 'bg-blue-100 text-blue-700',
    category: 'edicao',
    keywords: ['adicionar imagem pdf', 'inserir foto pdf', 'colocar logo pdf'],
  },
  {
    slug: 'assinar-pdf',
    name: 'Assinar PDF Online',
    shortName: 'Assinar PDF',
    description: 'Crie sua assinatura digital ou desenhe sua rubrica para assinar contratos em PDF.',
    icon: '✍️',
    color: 'bg-emerald-50',
    iconBg: 'bg-emerald-100 text-emerald-700',
    category: 'edicao',
    keywords: ['assinar pdf', 'assinar pdf online', 'rubrica em pdf', 'assinatura digital pdf'],
  },
  {
    slug: 'preencher-pdf',
    name: 'Preencher PDF',
    shortName: 'Preencher PDF',
    description: 'Preencha campos de formulários, selecione caixas de seleção e assine fichas em PDF.',
    icon: '📋',
    color: 'bg-purple-50',
    iconBg: 'bg-purple-100 text-purple-700',
    category: 'edicao',
    keywords: ['preencher pdf', 'preencher formulário pdf', 'ficha pdf'],
  },
  {
    slug: 'adicionar-marca-dagua-pdf',
    name: 'Adicionar Marca d\'Água',
    shortName: 'Marca d\'Água',
    description: 'Estampe textos como "CONFIDENCIAL", "RASCUNHO" ou seu logotipo em todas as páginas do PDF.',
    icon: '💧',
    color: 'bg-indigo-50',
    iconBg: 'bg-indigo-100 text-indigo-700',
    category: 'edicao',
    keywords: ['marca dagua pdf', 'adicionar marca dagua pdf', 'carimbo pdf'],
  },

  // ── OCR & TRANSCRIÇÃO ──────────────────────────────────────────────────────
  {
    slug: 'ocr-pdf',
    name: 'PDF para Texto (OCR)',
    shortName: 'PDF para Texto',
    description: 'Extraia o texto de PDFs digitalizados e escaneados usando reconhecimento óptico de caracteres.',
    icon: '👁️',
    color: 'bg-violet-50',
    iconBg: 'bg-violet-100 text-violet-700',
    category: 'ocr',
    keywords: ['ocr pdf', 'pdf para texto', 'reconhecimento de texto pdf', 'ocr online'],
  },
  {
    slug: 'imagem-para-texto',
    name: 'Imagem para Texto (OCR)',
    shortName: 'Imagem para Texto',
    description: 'Converta fotos de documentos, livros e placas em texto limpo e copiável.',
    icon: '📷',
    color: 'bg-fuchsia-50',
    iconBg: 'bg-fuchsia-100 text-fuchsia-700',
    category: 'ocr',
    keywords: ['imagem para texto', 'foto para texto', 'ocr imagem', 'extrair texto foto'],
  },
  {
    slug: 'ocr-online',
    name: 'OCR Online Grátis',
    shortName: 'OCR Online',
    description: 'Reconhecimento automático de caracteres em documentos e fotos com suporte ao português.',
    icon: '🔍',
    color: 'bg-purple-50',
    iconBg: 'bg-purple-100 text-purple-700',
    category: 'ocr',
    keywords: ['ocr online', 'ocr grátis', 'extrair texto escaneado'],
  },
  {
    slug: 'transcrever-video-em-texto',
    name: 'Transcrever Vídeo em Texto',
    shortName: 'Vídeo em Texto',
    description: 'Converta vídeos (MP4, WEBM, MOV) e áudios em texto limpo com exportação em PDF e Word.',
    icon: '🎙️',
    color: 'bg-emerald-50',
    iconBg: 'bg-emerald-100 text-emerald-700',
    category: 'ocr',
    keywords: ['transcrever vídeo', 'vídeo para texto', 'converter áudio em texto', 'áudio para pdf'],
  },
];
